// Learn cc.Class:
//  - [Chinese] http://docs.cocos.com/creator/manual/zh/scripting/class.html
//  - [English] http://www.cocos2d-x.org/docs/creator/en/scripting/class.html
// Learn Attribute:
//  - [Chinese] http://docs.cocos.com/creator/manual/zh/scripting/reference/attributes.html
//  - [English] http://www.cocos2d-x.org/docs/creator/en/scripting/reference/attributes.html
// Learn life-cycle callbacks:
//  - [Chinese] http://docs.cocos.com/creator/manual/zh/scripting/life-cycle-callbacks.html
//  - [English] http://www.cocos2d-x.org/docs/creator/en/scripting/life-cycle-callbacks.html

cc.Class({
    extends: cc.Component,

    properties: {
        // foo: {
        //     // ATTRIBUTES:
        //     default: null,        // The default value will be used only when the component attaching
        //                           // to a node for the first time
        //     type: cc.SpriteFrame, // optional, default is typeof default
        //     serializable: true,   // optional, default is true
        // },
        // bar: {
        //     get () {
        //         return this._bar;
        //     },
        //     set (value) {
        //         this._bar = value;
        //     }
        // },
    },

    // LIFE-CYCLE CALLBACKS:

    // onLoad () {},

    start () {
        let x = UtilsNode.getRandom(2,2,10);
        for (var i = 0; i < this.node.children.length; i++) {
            let node = this.node.children[i];
            let name = node.name;
            let myAction  =null;
            switch (name) {

                case "bg2":
                case "bg3":
                case "bg5":
                case "bg6":
                     myAction = cc.repeatForever(cc.sequence(cc.moveBy(1, -5,0),cc.moveBy(1, 5,0)));
                    node.runAction(myAction)
                    break;
                case "bg4":
                case "bg1":
                     myAction = cc.repeatForever(cc.sequence(cc.rotateBy(1, 3),cc.rotateBy(1, -3)));
                    node.runAction(myAction)
                    break;
            }
        }

        // let myAction = cc.repeatForever(cc.sequence(cc.rotateBy(1, 5),cc.rotateBy(1, -5)));
        // this.node.runAction(myAction)
    },

    // update (dt) {},
});
